### ISSUE TITLE
For TI-83 plus code changes

### ISSUE THREAD

**Issue by timetoprogramok** [emmettnicholas/TI-BASIC-Minesweeper#3]
If you look at the code, lines 23-31 have As that need to be changed to A matrix
That should be all other than the fewer areas that have multiple lines of code in one line.
Great project for its age though!
-Cayson (timeetoprogramok)

**Comment by emmettnicholas** [comment]
Thanks! Just to make sure I'm understanding what you're saying, L23 is correct already, right? I.e. only L24-31 need fixing?

**Comment by timetoprogramok** [comment]
Yeah I'm pretty sure those are the lines, also I don't know if I did something wrong while recreating the code, but when ever I lose it says invalid dim instead of what it is supposed to do. I will probably re do the code to fix it.

**Comment by emmettnicholas** [comment]
Ah sorry about that. My TI 83+ and memories of how this works are long gone, but lemme know if you figure it out.
